### ISSUE TITLE
How to change top page displayed Tags

### ISSUE THREAD

**Issue by odin-bb** [TryGhost/Dope#10]
Good Morning and first of all, this theme looks great.

I just uploaded it to my site and I noticed that I cannot see anything other than the default tag on the front page. Also looking at the instructions, I have to install a couple things, however I am running my Ghost instance through a docker so those might not be possible. Is there a way to fix the front page without them or is it something that I would need?

Thank you!

**Comment by odin-bb** [comment]
Needed to add tags to the post to make them show. I got it. Thank you.

**Comment by minimaluminium** [comment]
Glad to hear you sorted it out. Yeah, the tags will be displayed only if they have at least one post attached.
