### ISSUE TITLE
Home page image slider order of images

### ISSUE THREAD

**Issue by jgrmvi** [TryGhost/Dope#14]
Is it possible to set the order of the home page image slides. It seems it is the alphanumberical order by default. Can it be changed? Thanks

**Comment by minimaluminium** [comment]
Hey @jgrmvi, it's possible to change the order of the tags. [This line](https://github.com/TryGhost/Dope/blob/master/index.hbs#L17) of code uses `#get` helper to fetch the tags, and you can use `order` attribute to play with the orders. Read more about the attribute [here](https://ghost.org/docs/themes/helpers/get/#order).
