### ISSUE TITLE
Strange behaviour of next/prev buttons

### ISSUE THREAD

**Issue by brendantko** [TryGhost/Dope#19]
Hi there, just new here. Thanks for the awesome theme.
I've installed a fresh copy of it onto my Ghost 4.0.1 and there is some strange behaviour with the next and prev buttons.

The whole design seems a bit off.  The website is http://redvan.studio
I'm on safari on MacOS, but I tried on my phone and it showed up the same on there.
Anyone else having an issue like this? Thanks for any help.
<img width="1337" alt="Screen Shot 2021-03-28 at 11 54 31 AM" src="https://user-images.githubusercontent.com/81510855/112748521-666d6100-8fbc-11eb-9083-65f8dfe95550.png">

**Comment by brendantko** [comment]
Sorry about close and re-open. Still figuring out Github

**Comment by minimaluminium** [comment]
Hey @brendantko, here's how it looks on Safari macOS on my side. Have you managed it somehow?

![Screen Shot 2021-03-29 at 10 20 07 AM](https://user-images.githubusercontent.com/1418797/112779082-85c9c400-9078-11eb-8508-225123611fd7.png)

**Comment by brendantko** [comment]
Hey yeah, I made a dumb mistake and didn't realize some form CSS from another plug in was interfering with the CSS of the navigation on here. My bad >.<  but it's all good now. Thanks for checking into it!
