### ISSUE TITLE
Is there an issue with how links are displayed in Dope?

### ISSUE THREAD

**Issue by LegendaryPatMan** [TryGhost/Dope#20]
Hey! 

I'm running Dope as the theme for my blog. I've had the blog since Ghost 0.9 or something like that. I updated the blog to 4.0 and started rebuilding the content to work with Dope, but noticed that links to quotes such as below do not underline the whole link. The quotes are done via Markdown as I find them more consistent than using the regular editor. 

![The first issue,](https://user-images.githubusercontent.com/7371876/120213376-077dcf80-c22b-11eb-8312-b2f46a3d2e60.PNG)

The issue is also in links in paragraphs, not using Markdown, but the regular editor such as below, where some links are displayed correctly, others are half underlined and some have no underling at all 

![Capture](https://user-images.githubusercontent.com/7371876/120214037-d2be4800-c22b-11eb-85aa-d8eee5e35b68.PNG)

I thought this may have resulted from the blog being really old, so I transitioned to a brand new server, with a fresh install of 4.0, following the provided guide on the docs on 20.04 and copying all the old content over. And I got the same issue. In case something was an issue I fired up a second new server and did another fresh install, only coping a post from the editor to the new blog and I get the same issue. I even went so far as to just clone the repo and upload that to the server as the theme and still no luck

**Comment by minimaluminium** [comment]
Hey @LegendaryPatMan, thanks for the report. This was just fixed in the latest version. You can now download the theme and install it again.

**Comment by LegendaryPatMan** [comment]
Awesome! Thank you! Is there somewhere I can donate to the project as thanks?

**Comment by minimaluminium** [comment]
You're welcome! We have a donations section on our "Contributing to Ghost" page which you can read more about it [here](https://ghost.org/docs/contributing/#donations) 🙂
