### ISSUE TITLE
Post image overlaps content on Safari

### ISSUE THREAD

**Issue by manikal** [TryGhost/Dope#3]
Hi everyone,

The post image when scrolled down starts to overlap the content below, it jumps out of the post image box on Safari.
Image also disappears if scrolled down to the bottom and appears again if scrolled up to the top.

I'm using Safari 14.0.1 (haven't tested earlier versions) and it could be reproduced on https://dope.ghost.io (any post).

[Video](https://streamable.com/wky3h0) of the issue.

**Comment by minimaluminium** [comment]
Hey Mijo, the issue was fixed in https://github.com/TryGhost/Dope/commit/d003116a6fa6e881907271c5ed026189148dd0c8. Thanks for your detailed feedback 🙂
