### ISSUE TITLE
Home page has no image slider and prev/next buttons

### ISSUE THREAD

**Issue by andrewdefries** [TryGhost/Dope#4]
Hello, I have installed ghost and uploaded your theme zip without errors. For some reason the home page does show the image slider and the prev/next buttons. Can you please advise me how to format my homepage to look exactly as your example (https://dope.ghost.io/)? I am new to ghost, so if I am missing something obvious I appreciate your guidance!

My ghost blog is here:
http://134.122.9.102/

**Comment by at0dd** [comment]
The previous and next buttons automatically show if:
* There is more than one tag, provided each tag has at least one post.
* There are more tags than can fit on the screen at once.

**Comment by minimaluminium** [comment]
Hey @andrewdefries! Yes, @at0dd is right. You have currently 3 active tags, so there won't be any prev/next links on large screens. However, on smaller screens like iPad, they will be visible.

![134 122 9 102_(iPad)](https://user-images.githubusercontent.com/1418797/103494451-e2e71c80-4e71-11eb-891a-cac74353c3f4.png)

**Comment by andrewdefries** [comment]
Thank you all for the hand holding! Great ghost template!
